#! /bin/sh

for i in 0 1 2 3 4 5 6 7 8 9
do
for j in 0 1 2 3 4 5 6 7 8 9
do
for k in 0 1 2 3 4 5 6 7 8 9
do
    name=$i$j$k
    dfa=DFAs/DFA-$name
    echo generating sample for DFA $dfa
    bin/generateSample $dfa 2000 15 1800
    bin/generateSample $dfa 2500 15
    bin/generateSample $dfa 3000 15
done
done
done
