#! /bin/sh

# learn-V3 <name>

ARGS=
ARGS="$ARGS -DIncrementalCounts"
ARGS="$ARGS -DUseProductive"
ARGS="$ARGS -DComplement"

name=$1

bin/satin-run -server -Xmx512M $ARGS DfaInference.MDLFold \
    -input DFAs/DFA-$name -output learned.V3/Learned-$name > out.V3/out-$name 2>&1
